config/routes.rb
Rails.application.routes.draw do
  resources :locations do
    scope module: :locations do
      resources :reservations, only: [:new, :create]
    end
  end
  devise_for :owners
  devise_for :customers
  resource :booking, only: [:show], controller: :booking
  resources :active_reservations, only: [:index]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  authenticated :owner do
    root to: 'locations#index', as: :authenticated_owner_root
  end

  authenticated :customer do
    root to: 'booking#show', as: :authenticated_customer_root
  end

  # Defines the root path route ("/")
   root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
  has_many :reservations
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :reservations

  def within_operating_hours(reservation_date)
    reservation_time = Time.parse(reservation_date.to_s)
    reservation_time.strftime("%H%M%S%N") > opening_time.strftime("%H%M%S%N") && 
    reservation_time.strftime("%H%M%S%N") < closing_time.strftime("%H%M%S%N")
  end
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :location
  belongs_to :customer

  delegate :email, to: :customer, prefix: true
end

app/controllers/active_reservations_controller.rb
class ActiveReservationsController < ApplicationController
  def index
    @reservations = current_customer.reservations
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
  def show
    @locations = Location.all
  end
end

app/controllers/locations/reservations_controller.rb
module Locations
  class ReservationsController < ApplicationController
    before_action :set_location

    def new
      @reservation = @location.reservations.new
    end

    def create
      @reservation = @location.reservations.new(reservation_date: params[:reservation_date])
      @reservation.customer = current_customer
      if @location.within_operating_hours(@reservation.reservation_date)
        before_date = @reservation.reservation_date - 15.minutes
        after_date = @reservation.reservation_date + 15.minutes
        if @location.reservations.where(reservation_date: before_date..after_date).count >= @location.table_limit
          redirect_to new_location_reservation_path(@location), alert: "Selected time is already booked, Please choose a new time"
        else
          @reservation.save!
          redirect_to booking_path, notice: "Your reservation is successfully booked"
        end
      else
        redirect_to new_location_reservation_path(@location), alert: "Your reservation time is outside of the reservation hours"
      end 
    end

    private

    def set_location
      @location = Location.find(params[:location_id])
    end


  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[ show edit update destroy ]

  # GET /locations or /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1 or /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations or /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to location_url(@location), notice: "Location was successfully created." }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to location_url(@location), notice: "Location was successfully updated." }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy!

    respond_to do |format|
      format.html { redirect_to locations_url, notice: "Location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:name, :address, :table_limit, :opening_time, :closing_time )
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/active_reservations/_reservation.html.erb
<div class="bg-gray-300 p-2 flex flex-col gap-4">
  <p class="text-2xl"> Your reservation is booked for <%= reservation.reservation_date.strftime("%B %-d %Y, at %I:%M%P") %> </p>
</div>

app/views/active_reservations/index.html.erb
<div class="px-4 pt-8">
  <h1 class="text-5xl text-gray-700"> Your active reservations </h1>

  <br/>
  <div class="grid gap-4">
    <% @reservations.each do |reservation| %>
      <%= render "reservation", reservation: reservation %>
    <% end %>
  </div>
</div>

app/views/booking/_location.html.erb
<div class="bg-gray-300 gap-4 p-4">
  <p class="text-lg">
    <%= location.name %>
  </p>

  <p class="text-lg">
    <%= location.address %>
  </p>

  <p class="text-lg">
    <%= location.table_limit %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Opens At:</strong>
    <%= location.opening_time.strftime("%l:%M%p") %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Closes At:</strong>
    <%= location.closing_time.strftime("%l:%M%p") %>
  </p>

  </br>

  <%= link_to "Book Reservation", new_location_reservation_path(location), class: "bg-blue-500 text-blue-100 p-2 rounded-lg" %>
</div>

app/views/booking/show.html.erb
<div class="px-4 pt-8">
  <h1 class="text-4xl"> Browse Restaurant Locations </h1>
  <br/>
  <div class="flex justify-end">
    <%= link_to "View  #{current_customer.reservations.count} reservations", active_reservations_path, class: "bg-purple-500 p-2 rounded-lg text-purple-100" %>
  </div>
  <div class="px-8 grid md:grid-cols-4 gap-4 mt-8">
    <% @locations&.each do |location| %>
      <%= render "location", location: location %>
    <% end %>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestrauntReservations</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <main class="container mx-auto mt-28 px-5 flex">
      <%= render "layouts/alerts" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, class: "contents") do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_field :address, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :table_limit %>
    <%= form.number_field :table_limit, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :opening_time %>
    <%= form.time_field :opening_time, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :closing_time %>
    <%= form.time_field :closing_time, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/locations/_location.html.erb
<div id="<%= dom_id location %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= location.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= location.address %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Table limit:</strong>
    <%= location.table_limit %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Opening Time:</strong>
    <%= location.opening_time.strftime("%l:%M%p") %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Closing Time:</strong>
    <%= location.closing_time.strftime("%l:%M%p") %>
  </p>

</div>

app/views/locations/_reservation.html.erb
<div class="bg-gray-300 p-2">
  <p class="text-lg"> <%= reservation.customer_email %> has booked a reservation for <%= reservation.reservation_date.strftime("%B %-d %Y, at %I:%M%P") %> </p>
</div>

app/views/locations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing location</h1>

  <%= render "form", location: @location %>

  <%= link_to "Show this location", @location, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to locations", locations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/locations/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Locations" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Locations</h1>
    <%= link_to "New location", new_location_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="locations" class="min-w-full">
    <% @locations.each do |location| %>
      <%= render location %>
      <p>
        <%= link_to "Show this location", location, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/locations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New location</h1>

  <%= render "form", location: @location %>

  <%= link_to "Back to locations", locations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/locations/reservations/new.html.erb
<div class="flex flex-col items-center px-8 pt-8">
  <h1 class="text-5xl"> Book a reservation at <%= @location.name %> </h1>

  <%= form_with url: location_reservations_path(@location) do |f| %>
    <%= f.label :reservation_date %>
    <%= f.datetime_field :reservation_date %>

    <%= f.submit "Check Reservation", class: "bg-green-500 text-green-50 p-2 rounded-lg" %>
  <% end %>
</div>

app/views/locations/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @location %>

    <div class="grid gap-4"> 
      <% @location.reservations.each do |reservation| %>
        <%= render "reservation", reservation: reservation %>
      <% end %>
    </div>

    <%= link_to "Edit this location", edit_location_path(@location), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to locations", locations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this location", @location, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="flex flex-col items-center w-full pt-16 bg-gradient-to-b from-black-500 to-white-500 min-h-[100vh]">
  <h1 class="font-bold text-6xl text-purple-500">Seated</h1>
  <p class="text-lg text-gray-400">
    Simple reservations for Restaurants on Rails 
  </p>
  <div class="flex items-center gap-4 mt-8">
    <%= link_to "Sign in as customer", new_customer_session_path, class: "bg-blue-500 text-blue-50 p-2 rounded-lg" %>
    <%= link_to "Sign in as owner", new_owner_session_path, class: "bg-blue-500 text-blue-50 p-2 rounded-lg" %>
  </div>
</div>